/* ===========================
   ELIMINATOR — v27 shell + v19 core
=========================== */
const $ = (id)=>document.getElementById(id);
const $$ = (sel, root=document)=>Array.from(root.querySelectorAll(sel));
const clamp = (n,a,b)=>Math.max(a, Math.min(b,n));
const uid = ()=>Math.random().toString(36).slice(2,10)+"_"+Date.now().toString(36);
const nowISO = ()=>new Date().toISOString();
const dayKey = (d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
function safeClone(obj){ if(typeof structuredClone === "function"){ try{return structuredClone(obj);}catch(_){} } return JSON.parse(JSON.stringify(obj)); }

const LS_KEY = "eliminator_v27_shell_v19_core";
const SEASONS = ["printemps","ete","automne","hiver","noirblanc"];
const seasonLabel = (s)=>({printemps:"Printemps",ete:"Été",automne:"Automne",hiver:"Hiver",noirblanc:"Noir & blanc"}[s] || "Automne");
const SUBLINES = [
  "Une quête après l’autre.",
  "Le chaos recule, toi tu avances.",
  "Mission : calmer le bazar. Avec panache.",
  "Le destin a peur de ta to-do.",
  "Aujourd’hui, on taille dans le gras du chaos."
];
const pickSubline = ()=>SUBLINES[Math.floor(Math.random()*SUBLINES.length)];
function svgUrl(svg){ return `url("data:image/svg+xml,${encodeURIComponent(svg).replace(/'/g,'%27').replace(/"/g,'%22')}")`; }
const DOODLES = {
  printemps: svgUrl(`<svg xmlns="http://www.w3.org/2000/svg" width="520" height="520" viewBox="0 0 520 520"><g fill="none" stroke="rgba(255,120,170,0.55)" stroke-width="2" stroke-linecap="round"><path d="M90 120c30-30 65-30 95 0-30 30-65 30-95 0z"/><path d="M180 160c12-20 26-32 42-36-5 18-18 34-42 36z"/><path d="M360 110c28-22 60-22 88 0-28 22-60 22-88 0z"/></g><g fill="none" stroke="rgba(120,207,168,0.50)" stroke-width="2" stroke-linecap="round"><path d="M120 360c28-26 58-26 86 0-28 26-58 26-86 0z"/><path d="M330 360c22-34 44-48 70-52-6 26-26 48-70 52z"/></g></svg>`),
  ete: svgUrl(`<svg xmlns="http://www.w3.org/2000/svg" width="520" height="520" viewBox="0 0 520 520"><g fill="none" stroke="rgba(242,178,75,0.55)" stroke-width="2" stroke-linecap="round"><circle cx="120" cy="120" r="22"/><path d="M120 86v-18M120 172v18M86 120H68M172 120h18M96 96l-12-12M144 144l12 12M96 144l-12 12M144 96l12-12"/></g><g fill="none" stroke="rgba(90,190,200,0.45)" stroke-width="2" stroke-linecap="round"><path d="M300 120c30-20 62-20 92 0-30 20-62 20-92 0z"/><path d="M90 360c40 20 80 20 120 0"/><path d="M290 380c40 20 80 20 120 0"/></g></svg>`),
  automne: svgUrl(`<svg xmlns="http://www.w3.org/2000/svg" width="520" height="520" viewBox="0 0 520 520"><g fill="none" stroke="rgba(211,138,92,0.55)" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M110 140c40-20 70-10 90 10-20 30-60 40-90 10z"/><path d="M155 130c-8-18-10-34-6-52"/><path d="M360 140c40-20 70-10 90 10-20 30-60 40-90 10z"/><path d="M405 130c-8-18-10-34-6-52"/></g><g fill="none" stroke="rgba(140,110,85,0.45)" stroke-width="2" stroke-linecap="round"><path d="M120 360c26-22 54-22 80 0-26 22-54 22-80 0z"/><path d="M320 380c26-22 54-22 80 0-26 22-54 22-80 0z"/></g></svg>`),
  hiver: svgUrl(`<svg xmlns="http://www.w3.org/2000/svg" width="520" height="520" viewBox="0 0 520 520"><g fill="none" stroke="rgba(120,160,200,0.55)" stroke-width="2" stroke-linecap="round"><path d="M120 120l22 22M142 120l-22 22M120 98v44M98 120h44"/><path d="M360 140l26 26M386 140l-26 26M360 112v56M332 140h56"/></g><g fill="none" stroke="rgba(220,240,255,0.35)" stroke-width="2" stroke-linecap="round"><path d="M100 360c40-16 80-16 120 0"/><path d="M290 380c40-16 80-16 120 0"/></g></svg>`),
  noirblanc: svgUrl(`<svg xmlns="http://www.w3.org/2000/svg" width="520" height="520" viewBox="0 0 520 520"><g fill="none" stroke="rgba(0,0,0,0.35)" stroke-width="2" stroke-linecap="round"><path d="M110 140c40-20 70-10 90 10-20 30-60 40-90 10z"/><path d="M360 140c40-20 70-10 90 10-20 30-60 40-90 10z"/><circle cx="120" cy="360" r="18"/><circle cx="360" cy="380" r="18"/></g></svg>`)
};
const THEMES = {
  printemps:{clair:{bg:"#F9F7EC",fg:"#15120F",muted:"#5E5A54",barFill:"#7CCFA8",barEmpty:"rgba(124,207,168,.16)",barEdge:"rgba(255,255,255,.86)",accent:"rgba(255,162,190,.14)",accent2:"rgba(124,207,168,.30)",panel:"rgba(255,255,255,.72)",line:"rgba(0,0,0,.10)",glass:"rgba(255,255,255,.60)",glass2:"rgba(255,255,255,.42)",decoA:"rgba(255,162,190,.14)",decoB:"rgba(255,220,140,.10)"},sombre:{bg:"#2A3A3A",fg:"#F6F2EA",muted:"#DAD2C6",barFill:"#8FE3BC",barEmpty:"rgba(143,227,188,.12)",barEdge:"rgba(255,255,255,.20)",accent:"rgba(255,170,200,.10)",accent2:"rgba(143,227,188,.20)",panel:"rgba(54,86,82,.56)",line:"rgba(255,255,255,.14)",glass:"rgba(56,86,82,.40)",glass2:"rgba(72,110,104,.24)",decoA:"rgba(255,170,200,.08)",decoB:"rgba(255,235,180,.06)"}},
  ete:{clair:{bg:"#FFF6DF",fg:"#16120F",muted:"#6C5E52",barFill:"#F2B24B",barEmpty:"rgba(242,178,75,.16)",barEdge:"rgba(255,255,255,.88)",accent:"rgba(90,190,200,.12)",accent2:"rgba(242,178,75,.28)",panel:"rgba(255,255,255,.70)",line:"rgba(0,0,0,.10)",glass:"rgba(255,255,255,.60)",glass2:"rgba(255,255,255,.42)",decoA:"rgba(242,178,75,.14)",decoB:"rgba(90,190,200,.10)"},sombre:{bg:"#263748",fg:"#F0FAFF",muted:"#D6E2EA",barFill:"#FFD07A",barEmpty:"rgba(255,208,122,.12)",barEdge:"rgba(255,255,255,.20)",accent:"rgba(255,208,122,.10)",accent2:"rgba(134,210,220,.18)",panel:"rgba(54,86,108,.56)",line:"rgba(255,255,255,.14)",glass:"rgba(54,86,108,.38)",glass2:"rgba(72,110,136,.24)",decoA:"rgba(255,208,122,.08)",decoB:"rgba(134,210,220,.08)"}},
  automne:{clair:{bg:"#FBF4E8",fg:"#14120F",muted:"#6A5D53",barFill:"#D38A5C",barEmpty:"rgba(211,138,92,.18)",barEdge:"rgba(255,255,255,.85)",accent:"rgba(211,138,92,.18)",accent2:"rgba(211,138,92,.36)",panel:"rgba(255,255,255,.70)",line:"rgba(0,0,0,.10)",glass:"rgba(255,255,255,.58)",glass2:"rgba(255,255,255,.40)",decoA:"rgba(211,138,92,.12)",decoB:"rgba(255,210,160,.12)"},sombre:{bg:"#2E3A33",fg:"#FFF3E6",muted:"#E3D3C4",barFill:"#E0A77D",barEmpty:"rgba(224,167,125,.12)",barEdge:"rgba(255,255,255,.20)",accent:"rgba(224,167,125,.12)",accent2:"rgba(224,167,125,.22)",panel:"rgba(62,82,70,.56)",line:"rgba(255,255,255,.14)",glass:"rgba(62,82,70,.38)",glass2:"rgba(74,98,84,.24)",decoA:"rgba(224,167,125,.10)",decoB:"rgba(255,245,210,.08)"}},
  hiver:{clair:{bg:"#F5F7FA",fg:"#141B22",muted:"#61707E",barFill:"#78A0C8",barEmpty:"rgba(120,160,200,.18)",barEdge:"rgba(255,255,255,.88)",accent:"rgba(120,160,200,.16)",accent2:"rgba(120,160,200,.30)",panel:"rgba(255,255,255,.74)",line:"rgba(0,0,0,.10)",glass:"rgba(255,255,255,.58)",glass2:"rgba(255,255,255,.40)",decoA:"rgba(120,160,200,.12)",decoB:"rgba(220,240,255,.14)"},sombre:{bg:"#273244",fg:"#F0FBFF",muted:"#D0DFE5",barFill:"#9DB8D5",barEmpty:"rgba(157,184,213,.12)",barEdge:"rgba(255,255,255,.20)",accent:"rgba(157,184,213,.12)",accent2:"rgba(157,184,213,.22)",panel:"rgba(54,74,98,.56)",line:"rgba(255,255,255,.14)",glass:"rgba(54,74,98,.38)",glass2:"rgba(66,92,120,.24)",decoA:"rgba(157,184,213,.10)",decoB:"rgba(242,253,255,.08)"}},
  noirblanc:{clair:{bg:"#F7F4EE",fg:"#121212",muted:"#595959",barFill:"#4A4A4A",barEmpty:"rgba(0,0,0,.08)",barEdge:"rgba(255,255,255,.82)",accent:"rgba(0,0,0,.06)",accent2:"rgba(0,0,0,.12)",panel:"rgba(255,255,255,.74)",line:"rgba(0,0,0,.10)",glass:"rgba(255,255,255,.58)",glass2:"rgba(255,255,255,.40)",decoA:"rgba(0,0,0,.05)",decoB:"rgba(0,0,0,.03)"},sombre:{bg:"#2B2F38",fg:"#F4F4F4",muted:"#D5D5D8",barFill:"#BEBEBE",barEmpty:"rgba(255,255,255,.10)",barEdge:"rgba(255,255,255,.18)",accent:"rgba(255,255,255,.08)",accent2:"rgba(255,255,255,.14)",panel:"rgba(58,64,78,.56)",line:"rgba(255,255,255,.14)",glass:"rgba(58,64,78,.40)",glass2:"rgba(72,80,98,.26)",decoA:"rgba(255,255,255,.06)",decoB:"rgba(255,255,255,.04)"}}
};
const defaultState = {
  ui:{ mode:"clair", season:"automne", serious:false, focus:false, font:"yomogi", baseSize:16, leftW:360, rightW:420, progressStyle:"float" },
  settings:{ fatigue:2, motivation:2, listSort:"smart", keepListInFocus:true, includedCats:[], celebrationChance:.28, tipsChance:.18, tipsMinGapMin:6 },
  baseline:{ totalTasks:0, totalEtorions:0 },
  tasks:[], currentTaskId:null, currentTaskStart:null, undo:[],
  kiffances:["Respire 30 secondes comme une créature légendaire.","Range 10 objets comme un ninja du tri.","Bois une gorgée d’eau : potion de clarté mentale."],
  pomodoro:{ workMin:25, breakMin:5, autoStart:"auto", phase:"work" },
  notes:{ text:"", reminders:"", typhonse:[] },
  habits:[],
  history:[],
  stats:{ etorionsDone:0, tasksDone:0, sessions:0, taskHistory:[] },
  sets:{
    hospital:{ enabled:true, patients:4, itemsPerPatient:["Voir patient","Note","Traitement","Dossier"], checks:{} },
    consult:{ enabled:true, patients:6, itemsPerPatient:["Voir patient","Note","Ordonnance","Dossier"], checks:{} }
  }
};
function deepAssign(t,s){ for(const k in s){ if(s[k] && typeof s[k]==="object" && !Array.isArray(s[k]) && t[k]) deepAssign(t[k], s[k]); else t[k]=s[k]; } }
function loadState(){ try{ const raw=localStorage.getItem(LS_KEY); if(!raw) return safeClone(defaultState); const parsed=JSON.parse(raw); const merged=safeClone(defaultState); deepAssign(merged, parsed); return normalizeState(merged); }catch(_){ return safeClone(defaultState); } }
function normalizeState(s){
  if(Array.isArray(s.notes)) s.notes = { text:"", reminders:"", typhonse:[], entries:s.notes };
  if(!s.notes || typeof s.notes !== 'object') s.notes = { text:"", reminders:"", typhonse:[] };
  if(!Array.isArray(s.notes.typhonse)) s.notes.typhonse = [];
  if(!Array.isArray(s.habits)) s.habits = [];
  if(!Array.isArray(s.history)) s.history = [];
  if(!Array.isArray(s.tasks)) s.tasks = [];
  if(!s.stats) s.stats = { etorionsDone:0, tasksDone:0, sessions:0, taskHistory:[] };
  if(!Array.isArray(s.stats.taskHistory)) s.stats.taskHistory = [];
  if(!s.settings) s.settings = safeClone(defaultState.settings);
  if(!s.sets) s.sets = safeClone(defaultState.sets);
  return s;
}
let state = loadState();
function saveState(){ try{ localStorage.setItem(LS_KEY, JSON.stringify(state)); }catch(_){} }
function pushUndo(label){ state.undo.unshift({ label, at:Date.now(), payload:safeClone(state) }); state.undo = state.undo.slice(0, 25); saveState(); }
function doUndo(){ const snap=state.undo.shift(); if(!snap) return status("Rien à annuler."); state=snap.payload; saveState(); renderAll(); status("Retour : timeline réécrite."); }
let statusTimer=null;
function status(msg,ms=3500){ const el=$("statusSpot"); if(!el) return; el.textContent=msg||""; if(statusTimer) clearTimeout(statusTimer); if(msg) statusTimer=setTimeout(()=>el.textContent="",ms); }
function ensureNotes(){ if(!state.notes) state.notes = { text:"", reminders:"", typhonse:[] }; if(!Array.isArray(state.notes.typhonse)) state.notes.typhonse=[]; }
function estimateEtorions(title){
  const key = String(title||"").trim().toLowerCase();
  const hits = state.stats.taskHistory.filter(x=>x.key === key);
  if(!hits.length) return 1;
  const avg = hits.reduce((a,b)=>a + (b.etorionsUsed||1), 0) / hits.length;
  return clamp(Math.round(avg), 1, 12);
}
function isAllCapsLine(line){ const t=(line||"").trim(); if(!t) return false; const hasLetters=/[A-Za-zÀ-ÖØ-öø-ÿ]/.test(t); if(!hasLetters) return false; return t===t.toUpperCase() && t.length<=90; }
function parseTaskLine(line){ const raw=(line||"").trim(); if(!raw) return null; const cleaned=raw.replace(/^[-*•\s]+/,"").trim(); if(!cleaned) return null; let et=null; let title=cleaned; const m=cleaned.match(/^(.*?)(?:\s*[-–—]\s*|\s+)(\d+)\s*$/); if(m){ title=m[1].trim(); et=parseInt(m[2],10); } title=title.replace(/\s+/g," ").trim(); if(!title) return null; if(et!==null) et=clamp(et,1,99); return { title, etorions: et ?? estimateEtorions(title) }; }
function importFromInbox(text){
  const lines=String(text||"").split(/\r?\n/).map(l=>l.trim()).filter(Boolean); let cat="Inbox"; const imported=[];
  for(const line of lines){ if(isAllCapsLine(line)){ cat=line.trim(); continue; } const p=parseTaskLine(line); if(!p) continue; imported.push({ id:uid(), title:p.title, cat, etorionsTotal:p.etorions, etorionsLeft:p.etorions, initialEtorions:p.etorions, pinned:false, done:false, createdAt:nowISO(), doneAt:null }); }
  if(!imported.length) return 0;
  state.tasks.push(...imported);
  state.baseline.totalTasks += imported.length;
  state.baseline.totalEtorions += imported.reduce((a,t)=>a+t.etorionsTotal,0);
  ensureCurrentTask(); saveState(); renderAll(); return imported.length;
}
const activeTasks = ()=>state.tasks.filter(t=>!t.done).filter(t=>{ const inc=state.settings.includedCats||[]; return !inc.length || inc.includes(t.cat); });
const doneTasks = ()=>state.tasks.filter(t=>t.done);
const getTask = (id)=>state.tasks.find(t=>t.id===id) || null;
function ensureCurrentTask(){ const act=activeTasks(); if(!act.length){ state.currentTaskId=null; state.currentTaskStart=null; return; } const cur=getTask(state.currentTaskId); if(!cur || cur.done){ const pinned=act.find(t=>t.pinned); state.currentTaskId=(pinned||smartPool(act)[0]).id; state.currentTaskStart=Date.now(); } }
function ensureBaseline(){ if(state.baseline.totalTasks<=0 && state.tasks.length){ const act=activeTasks(); state.baseline.totalTasks=act.length; state.baseline.totalEtorions=act.reduce((a,t)=>a+t.etorionsTotal,0); } }
function remainingEtorions(){ return activeTasks().reduce((a,t)=>a + (t.etorionsLeft||0), 0); }
function computeRemainingPct(){ ensureBaseline(); const base=state.baseline.totalTasks||0; const rem=activeTasks().length; if(base<=0) return 100; return clamp(Math.round((rem/base)*100),0,100); }
function dopamineScore(){ const tasks=activeTasks(); if(!tasks.length) return 100; const avg=tasks.reduce((a,t)=>a+(t.etorionsLeft||1),0)/tasks.length; const score=Math.max(0, 100 - avg*10 - state.settings.fatigue*6 + state.settings.motivation*4); return clamp(Math.round(score),0,100); }
function smartPool(list){ const sorted=[...list].sort((a,b)=>{ if(a.pinned && !b.pinned) return -1; if(!a.pinned && b.pinned) return 1; return (a.etorionsLeft||0)-(b.etorionsLeft||0); }); return sorted; }
function roulettePick(){ const tasks=activeTasks(); if(!tasks.length) return null; const pool=smartPool(tasks).slice(0, Math.min(3, tasks.length)); return pool[Math.floor(Math.random()*pool.length)]; }
function selectTask(id){ const t=getTask(id); if(!t || t.done) return; state.currentTaskId=id; state.currentTaskStart=Date.now(); saveState(); renderHub(); renderTasksPanel(); }
function completeTask(id){ const t=getTask(id); if(!t || t.done) return; pushUndo('complete'); t.done=true; t.etorionsLeft=0; t.doneAt=nowISO(); state.stats.tasksDone += 1; state.stats.taskHistory.push({ key:t.title.trim().toLowerCase(), etorionsUsed:t.initialEtorions||t.etorionsTotal||1, date:nowISO() }); snapshotDay(); ensureCurrentTask(); saveState(); renderAll(); status("Glorieux. Une menace de moins."); }
function degommerOne(){ const t=getTask(state.currentTaskId); if(!t || t.done) return status("Aucune tâche à traiter."); pushUndo('degomme'); t.etorionsLeft = clamp((t.etorionsLeft||1)-1,0,99); state.stats.etorionsDone += 1; if(t.etorionsLeft<=0) completeTask(t.id); else { snapshotDay(); saveState(); renderAll(); status("💣 Éthorion dégommé."); } }
function restoreTask(id){ const t=getTask(id); if(!t || !t.done) return; pushUndo('restore'); t.done=false; t.doneAt=null; t.etorionsLeft=t.etorionsTotal; ensureCurrentTask(); saveState(); renderAll(); status("Ressuscitée. Suspect. Utile."); }
function moveTask(id,delta){ const idx=state.tasks.findIndex(t=>t.id===id); if(idx<0) return; const j=clamp(idx+delta,0,state.tasks.length-1); const [it]=state.tasks.splice(idx,1); state.tasks.splice(j,0,it); saveState(); renderAll(); }
function deleteTask(id){ const t=getTask(id); if(!t) return; pushUndo('delete'); state.tasks=state.tasks.filter(x=>x.id!==id); if(!t.done){ state.baseline.totalTasks=Math.max(0,state.baseline.totalTasks-1); state.baseline.totalEtorions=Math.max(0,state.baseline.totalEtorions - (t.etorionsTotal||0)); } if(state.currentTaskId===id) state.currentTaskId=null; ensureCurrentTask(); saveState(); renderAll(); status("Évaporée. Pouf."); }
function resetDay(){ pushUndo('resetDay'); state.tasks=[]; state.baseline={ totalTasks:0, totalEtorions:0 }; state.currentTaskId=null; state.currentTaskStart=null; state.stats.sessions += 1; saveState(); renderAll(); status("Reset total effectué."); }
function categories(){ const set=new Set(state.tasks.map(t=>t.cat||"Inbox")); const out=Array.from(set).sort((a,b)=>a.localeCompare(b)); out.unshift("Toutes"); return [...new Set(out)]; }
function sortTasks(list){ const mode=state.settings.listSort||"smart"; if(mode==="alpha") return [...list].sort((a,b)=>a.title.localeCompare(b.title,'fr')); if(mode==="cat") return [...list].sort((a,b)=>{ const c=(a.cat||"").localeCompare(b.cat||"",'fr'); return c!==0?c:a.title.localeCompare(b.title,'fr'); }); if(mode==="ordre") return [...list].sort((a,b)=>String(a.createdAt||"").localeCompare(String(b.createdAt||""))); return smartPool(list); }
function renderCatFilter(){ const sel=$("catFilter"); if(!sel) return; const prev=sel.value||"Toutes"; sel.innerHTML=""; const cats=categories(); for(const c of cats){ const opt=document.createElement('option'); opt.value=c; opt.textContent=c; sel.appendChild(opt); } sel.value=cats.includes(prev)?prev:"Toutes"; }
function renderProgress(){ const pct=computeRemainingPct(); const fill=$("progressFill"), pctEl=$("progressPctIn"), bar=$("progressBar"); if(fill) fill.style.width=`${pct}%`; if(pctEl) pctEl.textContent=`${pct}%`; if(bar) bar.setAttribute('aria-valuenow', String(pct)); }
function renderHub(){
  ensureCurrentTask(); ensureBaseline(); const act=activeTasks(); const done=doneTasks(); const cur=getTask(state.currentTaskId);
  $("subtitle").textContent = pickSubline();
  $("missionLineLeft").textContent = `Tâches en cours (${done.length} finies · ${act.length}/${state.baseline.totalTasks || act.length || 0})`;
  $("statActive").textContent=String(act.length); $("statDone").textContent=String(done.length); $("statEto").textContent=String(remainingEtorions());
  if(!cur){ $("taskTitle").textContent="Aucune tâche sélectionnée"; $("metaCat").textContent="—"; $("metaEt").textContent="—"; $("metaMin").textContent="—"; }
  else{ $("taskTitle").textContent=cur.title; $("metaCat").textContent=cur.cat||"Inbox"; $("metaEt").textContent=`${cur.etorionsLeft}/${cur.etorionsTotal}`; $("metaMin").textContent=`~${cur.etorionsLeft * state.pomodoro.workMin} min max`; }
  $("taskDoneBtn").disabled=!cur;
  $("countersBtn").textContent = `Compteurs ${act.length}/${state.baseline.totalTasks || act.length || 0}`;
}
function toggleTaskMeta(){ const m=$("taskMetaDetails"); if(!m) return; m.hidden=!m.hidden; }
function renderTasksPanel(){
  renderCatFilter(); const root=$("taskList"); if(!root) return; const cat=$("catFilter")?.value||"Toutes"; const view=$("viewFilter")?.value||"active";
  let list=state.tasks.slice(); if(view==="active") list=list.filter(t=>!t.done); if(view==="done") list=list.filter(t=>t.done); if(cat!=="Toutes") list=list.filter(t=>(t.cat||"Inbox")===cat); list=sortTasks(list);
  root.innerHTML=""; if(!list.length){ const d=document.createElement('div'); d.className='muted small'; d.textContent='Rien ici. Le néant a gagné.'; root.appendChild(d); return; }
  for(const t of list){ const row=document.createElement('div'); row.className='cardRow'; const left=document.createElement('div'); left.className='cardLeft'; const title=document.createElement('div'); title.className='cardTitle'; title.textContent=t.title; const sub=document.createElement('div'); sub.className='cardSub'; sub.textContent=`${t.cat||'Inbox'} · ${t.etorionsLeft}/${t.etorionsTotal} Éthorions${t.done?' · Fini':''}`; const stack=document.createElement('div'); stack.appendChild(title); stack.appendChild(sub); left.appendChild(stack); const btns=document.createElement('div'); btns.className='cardBtns'; if(!t.done){ [[t.id===state.currentTaskId?'★':'▶',()=>selectTask(t.id),'Sélectionner'],['📌',()=>{ t.pinned=!t.pinned; saveState(); renderAll(); },'Épingler'],['✓',()=>completeTask(t.id),'Terminer'],['↑',()=>moveTask(t.id,-1),'Monter'],['↓',()=>moveTask(t.id,1),'Descendre']].forEach(([txt,fn,title])=>{ const b=document.createElement('button'); b.className='iconBtn'; b.textContent=txt; b.title=title; b.onclick=fn; btns.appendChild(b); }); }
    else{ const b=document.createElement('button'); b.className='iconBtn'; b.textContent='↩'; b.title='Restaurer'; b.onclick=()=>restoreTask(t.id); btns.appendChild(b); }
    const del=document.createElement('button'); del.className='iconBtn'; del.textContent='×'; del.title='Supprimer'; del.onclick=()=>deleteTask(t.id); btns.appendChild(del);
    row.appendChild(left); row.appendChild(btns); root.appendChild(row); }
}
function renderKiffance(){ const root=$("kiffList"); if(!root) return; root.innerHTML=''; if(!state.kiffances.length){ const d=document.createElement('div'); d.className='muted small'; d.textContent='Aucune kiffance. Tragiquement austère.'; root.appendChild(d); return; } state.kiffances.forEach((k,idx)=>{ const row=document.createElement('div'); row.className='cardRow'; const left=document.createElement('div'); left.className='cardLeft'; const title=document.createElement('div'); title.className='cardTitle'; title.textContent=k; left.appendChild(title); const btns=document.createElement('div'); btns.className='cardBtns'; const del=document.createElement('button'); del.className='iconBtn'; del.textContent='×'; del.onclick=()=>{ pushUndo('kiffDel'); state.kiffances.splice(idx,1); saveState(); renderKiffance(); renderKiffOverlay(); status('Kiffance supprimée.'); }; btns.appendChild(del); row.appendChild(left); row.appendChild(btns); root.appendChild(row); }); }
function renderExport(){ const out=$("exportOut"); if(out) out.value=JSON.stringify(state,null,2); }
async function copyText(text){ try{ await navigator.clipboard.writeText(text); status('Copié.'); }catch(_){ status('Impossible de copier.'); } }
function fmtMMSS(ms){ const s=Math.max(0,Math.floor(ms/1000)); return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`; }
let pomoTimer=null, pomoRunning=false, remainingMs=0;
function currentPhaseMinutes(){ return state.pomodoro.phase === 'break' ? state.pomodoro.breakMin : state.pomodoro.workMin; }
function resetPhase(){ remainingMs = clamp(currentPhaseMinutes(),1,120) * 60 * 1000; const el=$("pomoTime"); if(el) el.textContent = fmtMMSS(remainingMs); }
function pausePomo(){ pomoRunning=false; if(pomoTimer) clearInterval(pomoTimer); $("pomoTime")?.classList.remove('running'); }
function tick(){ if(!pomoRunning) return; remainingMs -= 250; if(remainingMs<=0){ remainingMs=0; pausePomo(); state.pomodoro.phase = state.pomodoro.phase === 'work' ? 'break' : 'work'; saveState(); resetPhase(); status(`⏰ ${state.pomodoro.phase === 'work' ? 'Pomodoro' : 'Pause'} terminé.`); if(state.pomodoro.autoStart === 'auto') togglePomo(); } $("pomoTime").textContent = fmtMMSS(remainingMs); }
function togglePomo(){ if(pomoRunning){ pausePomo(); return; } if(remainingMs<=0) resetPhase(); pomoRunning=true; $("pomoTime")?.classList.add('running'); if(pomoTimer) clearInterval(pomoTimer); pomoTimer=setInterval(tick,250); }
function openModalBack(){ $("modalBack").hidden=false; }
function closeModalBackIfNone(){ const none = $("pomoModal").hidden && $("overlayModal").hidden; if(none) $("modalBack").hidden=true; }
function openPomoModal(){ $("pomoMinutes").value=String(state.pomodoro.workMin); $("breakMinutes").value=String(state.pomodoro.breakMin); $("autoStartSel").value=state.pomodoro.autoStart; openModalBack(); $("pomoModal").hidden=false; }
function closePomoModal(){ $("pomoModal").hidden=true; closeModalBackIfNone(); }
function applyPomoSettings(){ const w=clamp(parseInt($("pomoMinutes").value,10)||25,5,90); const b=clamp(parseInt($("breakMinutes").value,10)||5,1,30); const a=$("autoStartSel").value === 'manual' ? 'manual' : 'auto'; state.pomodoro.workMin=w; state.pomodoro.breakMin=b; state.pomodoro.autoStart=a; $("pomoQuick").value=String(w); saveState(); pausePomo(); state.pomodoro.phase='work'; resetPhase(); closePomoModal(); status('Pomodoro réglé.'); }
function hideAllOverlayPages(){ ['notes','typhonse','kiffance','stats'].forEach(k=>{ const el=$(`overlay-${k}`); if(el) el.hidden=true; }); }
function openOverlay(kind){ ensureNotes(); if(!$("pomoModal").hidden) closePomoModal(); hideAllOverlayPages(); const page=$(`overlay-${kind}`); if(!page) return; $("overlayTitle").textContent = kind === 'notes' ? 'Notes & rappels' : kind === 'typhonse' ? 'Typhonse' : kind === 'kiffance' ? 'Kiffance' : 'Stats'; page.hidden=false; openModalBack(); $("overlayModal").hidden=false; if(kind==='notes'){ $("notesArea").value=state.notes.text||''; $("remindersArea").value=state.notes.reminders||''; } if(kind==='typhonse') renderTyphonse(); if(kind==='kiffance') renderKiffOverlay(); if(kind==='stats') renderStatsOverlay(); }
function closeOverlay(){ $("overlayModal").hidden=true; closeModalBackIfNone(); }
let notesSaveTimer=null;
function scheduleNotesSave(){ if(notesSaveTimer) clearTimeout(notesSaveTimer); notesSaveTimer=setTimeout(()=>{ ensureNotes(); state.notes.text=$("notesArea")?.value||''; state.notes.reminders=$("remindersArea")?.value||''; $("notesMirror").value = state.notes.text; saveState(); status('Notes sauvegardées.',1500); },350); }
function renderTyphonse(){ ensureNotes(); const root=$("typhonseList"); if(!root) return; root.innerHTML=''; if(!state.notes.typhonse.length){ const d=document.createElement('div'); d.className='muted small'; d.textContent='Aucun item. Typhonse sommeille.'; root.appendChild(d); return; }
  for(const item of state.notes.typhonse){ const row=document.createElement('div'); row.className='cardRow'; const left=document.createElement('div'); left.className='tyLeft'; const cb=document.createElement('input'); cb.type='checkbox'; cb.className='tyCheck'; cb.checked=!!item.done; cb.onchange=()=>{ item.done=cb.checked; saveState(); renderTyphonse(); }; const txt=document.createElement('div'); txt.className='tyText' + (item.done ? ' done' : ''); txt.textContent=item.text; left.appendChild(cb); left.appendChild(txt); const del=document.createElement('button'); del.className='iconBtn'; del.textContent='×'; del.onclick=()=>{ state.notes.typhonse = state.notes.typhonse.filter(x=>x.id!==item.id); saveState(); renderTyphonse(); status('Typhonse : item évaporé.'); }; row.appendChild(left); row.appendChild(del); root.appendChild(row); }
}
function addTyphonse(){ const v=($("typhonseInput").value||'').trim(); if(!v) return; ensureNotes(); state.notes.typhonse.unshift({ id:uid(), text:v, done:false }); $("typhonseInput").value=''; saveState(); renderTyphonse(); status('Typhonse +1.'); }
function renderKiffOverlay(){ const root=$("kiffOverlayList"); if(!root) return; root.innerHTML=''; if(!state.kiffances.length){ const d=document.createElement('div'); d.className='muted small'; d.textContent='Aucune kiffance. Le désert.'; root.appendChild(d); return; }
  state.kiffances.forEach((k,idx)=>{ const row=document.createElement('div'); row.className='cardRow'; const left=document.createElement('div'); left.className='cardLeft'; const title=document.createElement('div'); title.className='cardTitle'; title.textContent=k; left.appendChild(title); const del=document.createElement('button'); del.className='iconBtn'; del.textContent='×'; del.onclick=()=>{ state.kiffances.splice(idx,1); saveState(); renderKiffance(); renderKiffOverlay(); }; row.appendChild(left); row.appendChild(del); root.appendChild(row); }); }
function addKiffOverlay(){ const v=($("kiffOverlayInput").value||'').trim(); if(!v) return; pushUndo('kiffAdd'); state.kiffances.unshift(v); $("kiffOverlayInput").value=''; saveState(); renderKiffance(); renderKiffOverlay(); status('Kiffance ajoutée.'); }
function snapshotDay(){ const dk=dayKey(); const doneToday=state.tasks.filter(t=>t.done && t.doneAt && t.doneAt.startsWith(dk)); const active=activeTasks(); const habitsSummary=(state.habits||[]).map(h=>({ name:h.name, done:h.checks.filter(Boolean).length, total:h.checks.length })); const entry={ day:dk, doneTitles:doneToday.map(t=>t.title), remainingTitles:active.map(t=>t.title), doneTasks:doneToday.length, remainingTasks:active.length, doneEtorions:state.stats.etorionsDone, baselineEtorions:state.baseline.totalEtorions, habits:habitsSummary, dopamine:dopamineScore() }; const idx=state.history.findIndex(x=>x.day===dk); if(idx>=0) state.history[idx]=entry; else state.history.unshift(entry); saveState(); }
function exportTodayText(){ snapshotDay(); const dk=dayKey(); const e=state.history.find(x=>x.day===dk); if(!e) return 'Aucune donnée.'; const lines=[]; lines.push(`ELIMINATOR — RAPPORT JOURNALIER — ${dk}`); lines.push(''); lines.push(`TÂCHES FAITES (${e.doneTasks})`); if(!e.doneTitles.length) lines.push('—'); else e.doneTitles.forEach(t=>lines.push(`- ${t}`)); lines.push(''); lines.push(`TÂCHES RESTANTES (${e.remainingTasks})`); if(!e.remainingTitles.length) lines.push('—'); else e.remainingTitles.forEach(t=>lines.push(`- ${t}`)); lines.push(''); lines.push(`HABITUDES`); if(!e.habits.length) lines.push('—'); else e.habits.forEach(h=>lines.push(`- ${h.name}: ${h.done}/${h.total}`)); lines.push(''); lines.push(`STATS`); lines.push(`- ÉTHORIONS DÉGOMMÉS: ${e.doneEtorions}`); lines.push(`- BASE ÉTHORIONS: ${e.baselineEtorions}`); lines.push(`- SCORE DOPAMINERGIQUE: ${e.dopamine}`); return lines.join('\n'); }
function setKeyItem(setName,pIndex,itemIndex){ return `${setName}|p${pIndex}|i${itemIndex}`; }
function initSetsChecksForToday(){ const dk=dayKey(); for(const key of ['hospital','consult']){ const s=state.sets[key]; if(!s.checks) s.checks={}; if(!s.checks[dk]) s.checks[dk]={}; } }
function toggleSetCheck(setName,pIndex,itemIndex){ initSetsChecksForToday(); const dk=dayKey(); const set=state.sets[setName]; const k=setKeyItem(setName,pIndex,itemIndex); set.checks[dk][k]=!set.checks[dk][k]; saveState(); renderSetsPanel(); snapshotDay(); }
function resetSetToday(setName){ initSetsChecksForToday(); const dk=dayKey(); state.sets[setName].checks[dk]={}; saveState(); renderSetsPanel(); snapshotDay(); }
function summarizeSetsToday(){ initSetsChecksForToday(); const dk=dayKey(); const out={}; for(const key of ['hospital','consult']){ const set=state.sets[key]; const checks=set.checks?.[dk]||{}; const total=set.patients * set.itemsPerPatient.length; const done=Object.values(checks).filter(Boolean).length; out[key]={ done,total }; } return out; }
function addHabit(name,slots){ const nm=(name||'').trim(); if(!nm) return; const sl=clamp(parseInt(slots,10)||8,3,12); state.habits.push({ id:uid(), name:nm, checks:Array.from({length:sl},()=>false), createdAt:nowISO() }); saveState(); renderHabitsPanel(); snapshotDay(); }
function renderHabitsPanel(){ const root=$("habitsPanelContent"); if(!root) return; root.innerHTML=''; if(!state.habits.length){ const d=document.createElement('div'); d.className='muted small'; d.textContent='Aucune habitude. Le terrain est vierge.'; root.appendChild(d); return; }
  state.habits.forEach(h=>{ const done=h.checks.filter(Boolean).length; const row=document.createElement('div'); row.className='cardRow'; const left=document.createElement('div'); left.className='cardLeft'; const txt=document.createElement('div'); txt.innerHTML=`<div class="cardTitle">${h.name}</div><div class="cardSub">${done}/${h.checks.length}</div>`; left.appendChild(txt); const btns=document.createElement('div'); btns.className='cardBtns'; h.checks.forEach((v,idx)=>{ const b=document.createElement('button'); b.className='iconBtn'; b.textContent=v?'✓':'·'; b.onclick=()=>{ h.checks[idx]=!h.checks[idx]; saveState(); renderHabitsPanel(); snapshotDay(); }; btns.appendChild(b); }); const del=document.createElement('button'); del.className='iconBtn'; del.textContent='×'; del.onclick=()=>{ state.habits=state.habits.filter(x=>x.id!==h.id); saveState(); renderHabitsPanel(); snapshotDay(); }; btns.appendChild(del); row.appendChild(left); row.appendChild(btns); root.appendChild(row); }); }
function renderSetsPanel(){ initSetsChecksForToday(); const root=$("setsPanelContent"); if(!root) return; const dk=dayKey(); root.innerHTML=''; for(const [key,label] of [["hospital","Hospitalier"],["consult","Consultation"]]){ const set=state.sets[key]; const checks=set.checks?.[dk]||{}; const total=set.patients*set.itemsPerPatient.length; const done=Object.values(checks).filter(Boolean).length; const card=document.createElement('div'); card.className='cardRow stackCard'; card.innerHTML=`<div class="stackHead"><div class="cardTitle">${label}</div><div class="cardSub">${done}/${total}</div></div>`; const wrap=document.createElement('div'); wrap.className='setGrid'; for(let p=1;p<=set.patients;p++){ const pDiv=document.createElement('div'); pDiv.className='setPatient'; const pTitle=document.createElement('div'); pTitle.className='cardSub'; pTitle.textContent=`Patient ${p}`; pDiv.appendChild(pTitle); set.itemsPerPatient.forEach((it,idx)=>{ const k=setKeyItem(key,p,idx); const row=document.createElement('button'); row.className='setCheck' + (checks[k] ? ' on' : ''); row.textContent = `${checks[k] ? '✓' : '·'} ${it}`; row.onclick=()=>toggleSetCheck(key,p,idx); pDiv.appendChild(row); }); wrap.appendChild(pDiv); } const reset=document.createElement('button'); reset.className='btn ghost'; reset.textContent="Reset aujourd'hui"; reset.onclick=()=>resetSetToday(key); card.appendChild(wrap); card.appendChild(reset); root.appendChild(card); } }
function renderCalendarPanel(){ const root=$("calendarPanelContent"); if(!root) return; const today=new Date(); const map={}; (state.history||[]).forEach(e=>map[e.day]=e.doneTasks||0); const max=Math.max(1,...Object.values(map),1); root.innerHTML=''; for(let i=29;i>=0;i--){ const d=new Date(today); d.setDate(today.getDate()-i); const key=dayKey(d); const v=map[key]||0; const cell=document.createElement('div'); cell.className='calCell'; cell.title=`${key} — ${v} tâche(s)`; const fill=document.createElement('div'); fill.className='calCellFill'; fill.style.opacity=String(0.08 + (v/max)*0.38); const txt=document.createElement('div'); txt.className='calCellText'; txt.textContent=String(d.getDate()).padStart(2,'0'); cell.appendChild(fill); cell.appendChild(txt); root.appendChild(cell); } }
function renderMoodPanel(){ $("moodFatigue").textContent=String(state.settings.fatigue); $("moodMotivation").textContent=String(state.settings.motivation); $("dopamineScore").textContent=String(dopamineScore()); }
function renderStatsOverlay(){ const act=activeTasks(); const done=doneTasks(); const pct=computeRemainingPct(); $("statsActiveBig").textContent=String(act.length); $("statsDoneBig").textContent=String(done.length); $("statsEtoBig").textContent=String(remainingEtorions()); $("statsPctBig").textContent=`${pct}%`; $("statsDopaBig").textContent=String(dopamineScore()); $("rightStatsContent").innerHTML = `<div class="cardRow"><div class="cardLeft"><div><div class="cardTitle">${state.stats.tasksDone}</div><div class="cardSub">Tâches finies cumulées</div></div></div></div><div class="cardRow"><div class="cardLeft"><div><div class="cardTitle">${state.stats.etorionsDone}</div><div class="cardSub">Éthorions dégommés</div></div></div></div><div class="cardRow"><div class="cardLeft"><div><div class="cardTitle">${dopamineScore()}</div><div class="cardSub">Score dopaminergique</div></div></div></div>`;
  const dump=[]; dump.push(`Actives: ${act.length}`); dump.push(`Finies: ${done.length}`); dump.push(`Éthorions restants: ${remainingEtorions()}`); dump.push(`Progression restante: ${pct}%`); dump.push(`Sessions reset: ${state.stats.sessions}`); dump.push(`Fatigue: ${state.settings.fatigue}`); dump.push(`Motivation: ${state.settings.motivation}`); dump.push(`Score dopaminergique: ${dopamineScore()}`); const hist=(state.history||[]).slice(0,7); if(hist.length){ dump.push(''); dump.push('Historique récent:'); hist.forEach(h=>dump.push(`- ${h.day}: ${h.doneTasks} faites, ${h.remainingTasks} restantes`)); } $("statsDump").value=dump.join('\n'); }
function openPanel(which){ $("panelBack").classList.add('show'); document.body.style.overflow='hidden'; if(which==='left'){ $("leftPanel").classList.add('open'); $("rightPanel").classList.remove('open'); } else { $("rightPanel").classList.add('open'); $("leftPanel").classList.remove('open'); } }
function closePanels(){ $("panelBack").classList.remove('show'); $("leftPanel").classList.remove('open'); $("rightPanel").classList.remove('open'); document.body.style.overflow=''; }
function initResizer(handleId, which){ const h=$(handleId); if(!h) return; let dragging=false,sx=0,sw=0; const down=(x)=>{ dragging=true; sx=x; sw = which==='left' ? state.ui.leftW : state.ui.rightW; }; const move=(x)=>{ if(!dragging) return; const dx=x-sx; if(which==='left') state.ui.leftW = clamp(sw+dx,320,980); else state.ui.rightW = clamp(sw-dx,320,980); applyTheme(); }; const up=()=>{ if(!dragging) return; dragging=false; saveState(); };
  h.addEventListener('mousedown',(e)=>{ e.preventDefault(); down(e.clientX); }); window.addEventListener('mousemove',(e)=>move(e.clientX)); window.addEventListener('mouseup', up); h.addEventListener('touchstart',(e)=>{ e.preventDefault(); down(e.touches[0].clientX); },{passive:false}); window.addEventListener('touchmove',(e)=>move(e.touches[0].clientX),{passive:true}); window.addEventListener('touchend', up);
}
function bindTabs(){ $$(".panel-left .tabBtn").forEach(btn=>btn.addEventListener('click',()=>{ $$(".panel-left .tabBtn").forEach(b=>b.classList.remove('active')); btn.classList.add('active'); const key=btn.dataset.lefttab; $$("#leftPanel .tabPage").forEach(p=>p.classList.remove('show')); $("left-"+key)?.classList.add('show'); if(key==='tasks') renderTasksPanel(); if(key==='kiffance') renderKiffance(); if(key==='prefs') syncPrefsUI(); if(key==='export') renderExport(); }));
  $$(".panel-right .tabBtn").forEach(btn=>btn.addEventListener('click',()=>{ $$(".panel-right .tabBtn").forEach(b=>b.classList.remove('active')); btn.classList.add('active'); const key=btn.dataset.righttab; $$("#rightPanel .tabPage").forEach(p=>p.classList.remove('show')); $("right-"+key)?.classList.add('show'); if(key==='sets') renderSetsPanel(); if(key==='habits') renderHabitsPanel(); if(key==='mood') renderMoodPanel(); if(key==='calendar') renderCalendarPanel(); if(key==='notes') { $("notesMirror").value = state.notes.text || ''; } if(key==='stats') renderStatsOverlay(); })); }
function syncPrefsUI(){ $("modeSel").value=state.ui.mode; $("seasonSel").value=state.ui.season; $("fontSel").value=state.ui.font; $("uiScale").value=String(state.ui.baseSize); $("progressStyleSel").value=state.ui.progressStyle; $("seriousSel").value=String(!!state.ui.serious); $("fatigueSel").value=String(state.settings.fatigue); $("motivationSel").value=String(state.settings.motivation); $("pomoQuick").value=String(state.pomodoro.workMin); }
function applyTheme(){ const season=(state.ui.season in THEMES) ? state.ui.season : 'automne'; const mode=state.ui.mode === 'sombre' ? 'sombre' : 'clair'; const t=THEMES[season][mode]; const setVar=(k,v)=>document.documentElement.style.setProperty(k,v); setVar('--bg',t.bg); setVar('--fg',t.fg); setVar('--muted',t.muted); setVar('--barFill',t.barFill); setVar('--barEmpty',t.barEmpty); setVar('--barEdge',t.barEdge); setVar('--accent',t.accent); setVar('--accent2',t.accent2); setVar('--panelBg',t.panel); setVar('--line',t.line); setVar('--glass',t.glass); setVar('--glass2',t.glass2); setVar('--decoA',t.decoA); setVar('--decoB',t.decoB); setVar('--baseSize',`${clamp(state.ui.baseSize,14,18)}px`); const maxPanel=Math.max(320, Math.min(window.innerWidth - 28, 520)); setVar('--leftW',`${clamp(state.ui.leftW,320,maxPanel)}px`); setVar('--rightW',`${clamp(state.ui.rightW,320,maxPanel)}px`); if(state.ui.progressStyle==='anchored'){ setVar('--progressShadow','inset 0 12px 22px rgba(0,0,0,.12)'); setVar('--progressBorder','1px solid rgba(0,0,0,.14)'); } else { setVar('--progressShadow','0 18px 30px rgba(0,0,0,.10)'); setVar('--progressBorder','1px solid var(--line)'); } setVar('--doodle', DOODLES[season] || DOODLES.automne); setVar('--doodleOpacity', mode==='sombre' ? '.16' : '.22'); document.body.setAttribute('data-font', state.ui.font); $("modeToggle").textContent = state.ui.mode === 'sombre' ? 'Sombre' : 'Clair'; $("modeToggle").setAttribute('aria-pressed', state.ui.mode === 'sombre' ? 'true' : 'false'); $("seasonCycle").textContent = seasonLabel(state.ui.season); $("seriousToggle").classList.toggle('active', !!state.ui.serious); $("seriousToggle").textContent = state.ui.serious ? 'Sérieux on' : 'Sérieux'; document.body.classList.toggle('focus-mode', !!state.ui.focus); document.body.classList.toggle('serious-mode', !!state.ui.serious); $("focusBtn").classList.toggle('active', !!state.ui.focus); $("focusDock").hidden = !state.ui.focus; }
function renderAll(){ renderProgress(); renderHub(); renderTasksPanel(); renderKiffance(); renderStatsOverlay(); renderSetsPanel(); renderHabitsPanel(); renderCalendarPanel(); renderMoodPanel(); renderExport(); applyTheme(); }
function wireEvents(){
  $("btnLeft").addEventListener('click',()=>openPanel('left')); $("btnRight").addEventListener('click',()=>openPanel('right')); $("leftClose").addEventListener('click', closePanels); $("rightClose").addEventListener('click', closePanels); $("panelBack").addEventListener('click', closePanels);
  $("modeToggle").addEventListener('click',()=>{ state.ui.mode = state.ui.mode === 'clair' ? 'sombre' : 'clair'; saveState(); renderAll(); });
  $("seasonCycle").addEventListener('click',()=>{ const i=SEASONS.indexOf(state.ui.season); state.ui.season = SEASONS[(i+1)%SEASONS.length]; saveState(); renderAll(); });
  $("seriousToggle").addEventListener('click',()=>{ state.ui.serious = !state.ui.serious; saveState(); renderAll(); });
  $("focusBtn").addEventListener('click',()=>{ state.ui.focus = !state.ui.focus; if(state.ui.focus && state.settings.keepListInFocus) openPanel('right'); saveState(); renderAll(); });
  $("countersBtn").addEventListener('click',()=>openOverlay('stats'));
  $("undoBtn").addEventListener('click', doUndo); $("rouletteBtn").addEventListener('click',()=>{ const wheel=$("rouletteWheel"); wheel.classList.remove('spinning'); void wheel.offsetWidth; wheel.classList.add('spinning'); const pick=roulettePick(); if(!pick){ status('Rien à tirer.'); return; } setTimeout(()=>{ state.currentTaskId=pick.id; state.currentTaskStart=Date.now(); saveState(); renderHub(); renderTasksPanel(); status('🎡 Tirage : ' + pick.title); }, 280); }); $("bombBtn").addEventListener('click', degommerOne); $("taskDoneBtn").addEventListener('click',()=>{ if(state.currentTaskId) completeTask(state.currentTaskId); }); $("taskInfoBtn").addEventListener('click', toggleTaskMeta);
  $("openNotes").addEventListener('click',()=>openOverlay('notes')); $("openTyphonse").addEventListener('click',()=>openOverlay('typhonse')); $("openKiffance").addEventListener('click',()=>openOverlay('kiffance')); $("openStats").addEventListener('click',()=>openOverlay('stats')); $("focusSetsBtn").addEventListener('click',()=>openPanel('right')); $("focusHabitsBtn").addEventListener('click',()=>{ openPanel('right'); $$(".panel-right .tabBtn").find(b=>b.dataset.righttab==='habits')?.click(); }); $("focusStatsBtn").addEventListener('click',()=>openOverlay('stats')); $("focusNotesBtn").addEventListener('click',()=>openOverlay('notes'));
  $("inboxAdd").addEventListener('click',()=>{ const n=importFromInbox($("inboxText").value); status(n ? `${n} tâche(s) importée(s).` : 'Rien importé.'); }); $("inboxClear").addEventListener('click',()=>$("inboxText").value=''); $("viewFilter").addEventListener('change', renderTasksPanel); $("catFilter").addEventListener('change', renderTasksPanel); $("sortSel").addEventListener('change',(e)=>{ state.settings.listSort=e.target.value; saveState(); renderTasksPanel(); });
  $("kiffAdd").addEventListener('click',()=>{ const v=($("kiffNew").value||'').trim(); if(!v) return; pushUndo('kiffAdd'); state.kiffances.unshift(v); $("kiffNew").value=''; saveState(); renderKiffance(); renderKiffOverlay(); status('Kiffance ajoutée.'); });
  $("prefsApply").addEventListener('click',()=>{ state.ui.mode=$("modeSel").value === 'sombre' ? 'sombre' : 'clair'; state.ui.season=$("seasonSel").value; state.ui.font=$("fontSel").value; state.ui.baseSize=clamp(parseInt($("uiScale").value,10)||16,14,18); state.ui.progressStyle=$("progressStyleSel").value === 'anchored' ? 'anchored' : 'float'; state.ui.serious=$("seriousSel").value === 'true'; state.settings.fatigue=clamp(parseInt($("fatigueSel").value,10)||2,0,4); state.settings.motivation=clamp(parseInt($("motivationSel").value,10)||2,0,4); state.pomodoro.workMin=clamp(parseInt($("pomoQuick").value,10)||25,5,90); saveState(); resetPhase(); renderAll(); status('Préférences appliquées.'); });
  $("prefsReset").addEventListener('click',()=>{ state.ui = safeClone(defaultState.ui); state.settings = safeClone(defaultState.settings); state.pomodoro = safeClone(defaultState.pomodoro); saveState(); syncPrefsUI(); resetPhase(); renderAll(); status('Prefs reset.'); });
  $("exportBtn").addEventListener('click',()=>copyText(JSON.stringify(state,null,2))); $("exportDayBtn").addEventListener('click',()=>copyText(exportTodayText())); $("wipeBtn").addEventListener('click', resetDay);
  $("pomoTime").addEventListener('click', togglePomo); $("pomoEdit").addEventListener('click',(e)=>{ e.preventDefault(); openPomoModal(); }); $("modalClose").addEventListener('click', closePomoModal); $("pomoApply").addEventListener('click', applyPomoSettings); $("pomoReset").addEventListener('click',()=>{ pausePomo(); state.pomodoro.phase='work'; resetPhase(); status('Timer reset.'); });
  $("modalBack").addEventListener('click',()=>{ if(!$("pomoModal").hidden) closePomoModal(); if(!$("overlayModal").hidden) closeOverlay(); closeModalBackIfNone(); }); $("overlayClose").addEventListener('click', closeOverlay);
  $("notesArea").addEventListener('input', scheduleNotesSave); $("remindersArea").addEventListener('input', scheduleNotesSave); $("notesMirror").addEventListener('input',()=>{ state.notes.text=$("notesMirror").value||''; saveState(); });
  $("typhonseAdd").addEventListener('click', addTyphonse); $("typhonseInput").addEventListener('keydown',(e)=>{ if(e.key==='Enter'){ e.preventDefault(); addTyphonse(); } }); $("typhonseClearDone").addEventListener('click',()=>{ state.notes.typhonse = state.notes.typhonse.filter(x=>!x.done); saveState(); renderTyphonse(); status('Typhonse : cochés retirés.'); });
  $("kiffOverlayAdd").addEventListener('click', addKiffOverlay); $("kiffOverlayInput").addEventListener('keydown',(e)=>{ if(e.key==='Enter'){ e.preventDefault(); addKiffOverlay(); } }); $("kiffRoll").addEventListener('click',()=>{ if(!state.kiffances.length) return status('Aucune kiffance à tirer.'); const k=state.kiffances[Math.floor(Math.random()*state.kiffances.length)]; status('🎁 Kiffance : ' + k); });
  $("habitAdd").addEventListener('click',()=>{ addHabit($("habitName").value,$("habitSlots").value); $("habitName").value=''; $("habitSlots").value='8'; });
  window.addEventListener('keydown',(e)=>{ if(e.key==='Escape'){ if(!$("pomoModal").hidden) closePomoModal(); if(!$("overlayModal").hidden) closeOverlay(); closePanels(); } }); window.addEventListener('resize', applyTheme);
}
function init(){ state = normalizeState(loadState()); ensureNotes(); bindTabs(); initResizer('leftResizer','left'); initResizer('rightResizer','right'); syncPrefsUI(); initSetsChecksForToday(); ensureBaseline(); ensureCurrentTask(); wireEvents(); if(!state.pomodoro.phase) state.pomodoro.phase='work'; resetPhase(); renderAll(); snapshotDay(); }
document.addEventListener('DOMContentLoaded', init);
